# Generated by Django 5.2.4 on 2025-07-05 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la Pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('texto', 'Entrada de Texto Libre'), ('calificacion', 'Escala de Calificación (1-5)'), ('seleccion_unica', 'Selección Única'), ('seleccion_multiple', 'Selección Múltiple'), ('booleano', 'Sí/No o Verdadero/Falso')], max_length=20, verbose_name='Tipo de Pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormularioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Formulario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('preguntas', models.ManyToManyField(related_name='formularios_asociados', to='core_evaluacion.pregunta', verbose_name='Preguntas del Formulario')),
            ],
            options={
                'verbose_name': 'Formulario de Evaluación',
                'verbose_name_plural': 'Formularios de Evaluación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=20, unique=True, verbose_name='ID Empleado')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_curso', to='core_evaluacion.curso', verbose_name='Curso Evaluado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_dadas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('formulario_evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_evaluacion.formularioevaluacion', verbose_name='Formulario Usado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to='core_evaluacion.profesor', verbose_name='Profesor Evaluado')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_envio'],
                'unique_together': {('estudiante', 'profesor', 'curso', 'formulario_evaluacion')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_impartidos', to='core_evaluacion.profesor', verbose_name='Profesor Asignado'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True, verbose_name='Respuesta de Texto')),
                ('respuesta_calificacion', models.IntegerField(blank=True, null=True, verbose_name='Respuesta de Calificación')),
                ('respuesta_booleana', models.BooleanField(blank=True, null=True, verbose_name='Respuesta Booleana')),
                ('respuesta_seleccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Respuesta de Selección')),
                ('respuesta_multiples_selecciones', models.JSONField(blank=True, null=True, verbose_name='Respuestas de Múltiple Selección')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core_evaluacion.evaluacion', verbose_name='Evaluación')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_evaluacion.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['pregunta__id'],
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
    ]
